name: Unlock Level 2

on:
  push:
    branches:
      - main

jobs:
  unlock-level:
    if: contains(github.event.head_commit.message, 'I am ready')
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 🔧 Set up Git
        run: |
          git config user.name "gitgames-bot"
          git config user.email "bot@gitgames.local"

      - name: 🕵️ Validate base64 input
        run: |
          if base64 -d levels/level2.b64 > /dev/null 2>&1; then
            echo "Base64 is valid!"
          else
            echo "❌ Invalid base64 input in level2.b64"
            exit 1
          fi

      - name: 🔓 Decode Level 2 Challenge (to levels/level2.txt)
        run: |
          base64 -d levels/level2.b64 > levels/level2.txt

      - name: 🚀 Commit and push level2.txt
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f "levels/level2.txt" ]; then
            git add levels/level2.txt
            git commit -m "Level 2 Unlocked" || echo "No changes to commit"
            git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
            git push
          else
            echo "Decoded level2.txt not found. Skipping commit."
          fi
