name: Unlock Level 2

on:
  push:
    branches:
      - main

jobs:
  unlock-level:
    if: contains(github.event.head_commit.message, 'I am ready')
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 🔧 Set up Git
        run: |
          git config user.name "gitgames-bot"
          git config user.email "bot@gitgames.local"

      - name: 🗂️ Create level2 folder
        run: mkdir -p level2

      - name: 🔓 Decode Level 2 Challenge
        run: |
          base64 -d levels/level2.b64 > level2/challenge2.txt

      - name: 🚀 Commit and push Level 2
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f "level2/challenge2.txt" ]; then
            git add level2/challenge2.txt
            git commit -m "Level 2 Unlocked" || echo "No changes to commit"
            git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
            git push
          else
            echo "Level 2 file not found. Skipping commit."
          fi
